# Project information
site_name: Пишем Telegram-ботов с aiogram 3.x
site_description: Учебник по разработке ботов для Telegram на языке Python при помощи фреймворка aiogram 3.x
site_author: MasterGroosha
site_url: https://mastergroosha.github.io/aiogram-3-guide
docs_dir: book_src
site_dir: docs

# Repository
repo_name: MasterGroosha/aiogram-3-guide
repo_url: https://github.com/MasterGroosha/aiogram-3-guide
edit_uri: ""

# Copyright
copyright: Copyright &copy; 2020-2023 Groosha

# Configuration
theme:
  name: material
  custom_dir: book_src/overrides
  language: ru
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: teal
      toggle:
        icon: material/brightness-4
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: teal
      toggle:
        icon: material/brightness-7
        name: Switch to light mode
  font:
    text: Roboto
    code: Roboto Mono
  icon:
    logo: material/robot

# Extras
extra:
  social:
    - icon: fontawesome/brands/telegram
      link: https://t.me/+DE0_2nCvbXozZjUy
      name: "Чат в Telegram"
    - icon: fontawesome/brands/github
      link: https://github.com/MasterGroosha/aiogram-3-guide
      name: GitHub

# Extensions
markdown_extensions:
  - admonition
  - pymdownx.highlight
  - pymdownx.superfences
  - meta
  - attr_list
  - toc:
      permalink: true

# Navigation
nav:
  - "home": index.md
  - "quickstart": quickstart.md
  - "messages": messages.md
  - "buttons": buttons.md
  - "routers": routers.md
  - "filters_and_middlewares": filters-and-middlewares.md
  - "special_updates": special-updates.md
  - "fsm": fsm.md
  - "inline_mode": inline-mode.md

# Plugins
plugins:
  - mkdocs-video:
      is_video: True
      video_autoplay: False
      video_type: mp4
      css_style:
        width: "100%"
        height: "100%"
  - search
  - i18n:
      docs_structure: folder
      reconfigure_search: true
      languages:
        - locale: ru
          default: true
          name: "<img style='height: 10px; border: 0px;' alt='ru' src='https://flagicons.lipis.dev/flags/4x3/ru.svg' title='russian' /> Русский"
          build: true
          nav_translations:
            "home": "Введение"
            "quickstart": "Знакомство с aiogram"
            "messages": "Работа с сообщениями"
            "buttons": "Кнопки"
            "routers": "Роутеры. Структура"
            "filters_and_middlewares": "Фильтры и мидлвари"
            "special_updates": "Особые апдейты"
            "fsm": "Конечные автоматы"
            "inline_mode": "Инлайн-режим"
        - locale: uz
          name: "<img style='height: 10px; border: 0px;' alt='uz' src='https://flagicons.lipis.dev/flags/4x3/uz.svg' title='uzbek' /> O'zbekcha"
          build: true
          site_name: "Aiogram 3.xda Telegram botlar yozamiz"
          nav_translations:
            "home": "Kirish"
            "quickstart": "Aiogram bilan tanishuv"
            "messages": "Xabarlar bilan ishlash"
            "buttons": "Tugmalar"
            "routers": "Routerlar. Struktura"
            "filters_and_middlewares": "Filtrlar va middlewarelar"
            "special_updates": "Maxsus yangilanishlar"
            "fsm": "FSM (Steytlar)"
            "inline_mode": "Inlayn-mode"

# Custom
nav_name:
  ru: "Оглавление"
  uz: "Mundarija"
